language: java
script:
  - mvn assembly:assembly
  - ls $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR/test
deploy:
  provider: releases
  secure: "Jr0O+3hAEN8VkJusbRi6oFnXmCqC+JNCWtmd3oT6bYuPgv+LcVXjdSwkrD7JlcLftBckVts2l2HMhft9wdq65FJWUL9noFzBvGr83wy7TJ3+YTBKz3MAo4zyHNkWoyO4KFYpSLvwnbt3TFb4rlwdWvBreHoQP/Akb5GePieUFKn3LwnadSVQmNp916LVhYMb2iIEhJLBSn93tYXqF9+GE24PL293zgXOz9RzTWXmYkFSSonbfBMsviq7m2IBRGwPobQae7cFPJPd5ckL8lMfSfndpPBc4RS39Yeqnc5k3nNexqnj3wIH+8u50J1EMCc31BvTCSlxVikV1R6Xh9VmvRvQAvItREtnPQrJX5PcNbYDe6Ay001bi8hBhfYjysaqh/0sX5UBfUMpyLxv6wZh2J4UPcGPCAXxx6gOUm3UU0gGCg3nzGOuqHAbAL990furRCid8jmWKavcz/nSbyx4r8OppgGEfO509KGpQl+e07zOuTkFLqDlUK0zVblW7kQ3k54qmi7SxshiTA9oTCjFhm3oB+HhBgp/x2X3xkvRFMW7/lqU2u0F0H75ZsrSGoIxfHNb2/0gNBmBMxWSgQg5yLdonStjOQzU2wqXAGZ4HaSp5/x0fZQlWuAFKvRsbM7qzgQpZlzlfGrqcQ8YN7xGRf/JMD3gLR0ClDfpt+xeqIo="
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
  branches:
    only:
      master